# Disrupting the Studio 

#### Keywords {-}
hollywood, script pars, greenlight, studio, nlp, cluster, pattern, information extract

## Why parse scripts?

The success of an entertainment studio is based on finding content that is unique and original. This process usually starts with a script being pitched to a studio. [@staiger_hybrid_1997]
It is normal for content creators to submit hundreds of scripts per week to a studio. If the studio likes what it sees, it greenlights the project and decides to fund it. The script is like the backbone of a movie or television series, and it forms a main storyline. They usually contain all details of the project, like dialogues of characters, setting of the scene, movements and actions of characters, and any other information that needs to be conveyed in addition to spoken content. 

Gathering information from scripts has traditionally been a manual process. Typically, a group of studio executives will meet after reading a script and use their "gut feeling" to assess what the potential market appeal of a project would be. They then make estimates on what the cost of production and marketing would be, and finally decide on whether that cost is worth the expected return. 

This manual intake makes the script filtering and selection process inefficient. This could result in a script that has the potential for becoming a future blockbuster go unnoticed or get buried in a pile of untouched scripts. The chance of this happening is higher if that new script comes from a small unknown creator. Due to the intake step being a highly manual process, this process tends to be laborious, inefficient, slow, prone to error, and susceptible to human bias.

## Old School Hollywood meets Silicon Valley

Advances in Natural Language Processing (NLP) and Unstructured Text Analytics can change the way scripts have traditionally been evaluated. Clustering content by term content can categorize texts without any supervision. Algorithms can interpret the context of text and use an inductive approach to drive the formation of metadata. Once a common set of metadata categories, tags and terms have been selected, application of Information Extraction (IE) and Pattern Recognition methods can allow for the processing and transformation of new unstructured text data into a semi-structured
form that can be reasoned with. [@murdoch_beyond_2018] This would allow for the computation of extracted information from scripts so that this information can be accessed and analyzed in a database system.

The intake process could also be refined. A template-like intake could be designed. This would be based on categorization that results from the aforementioned unstructured analysis. Writers would input elements of the script into these templates. They would still be given full creative freedom in terms of what text that they can enter, however, the templated input would allow algorithms to better pick up key features from new scripts. Once implemented, the new scripts (templates) could be fed into an algorithmic parser that had some foreknowledge on what each section in the template contained. The parser would extract relevant information and form a metadata dataset that could be accessed and searched for programmatically. For cold starting the algorithms, a training dataset that was built using the input templates and human annotation could be used. This collection of training data would be much like what the input process is now, except for the additional step of using an input template. 

After a script is algorithmically parsed, a human touch layer would be necessary so that any information that the algorithm did not pick up, or picked up incorrectly, could be added or changed in this application. This application would be integrated into the overall system architecture and different facets of the business would be able to benefit from having access to rich production metadata. This metadata dataset could include things like talent, scene setting, key actions and movements, assets used in the scene, dialogue attributes, and even scene sentiment.

In this manner, a framework that consists of a combination of both, unstructured and structured methods, can enrich and tag new scripts thereby allowing for easy search and discovery.

## A Work in Progress

The success of this project would be very beneficial for studios in the following ways. 

The intake and greenlighting process becomes much more efficient since studios will now be able to scale up the number of scripts they can review. This in turn will allow them to place better bets on what projects to greenlight. 

Accessing information in the metadata dataset can allow for more efficient budget allocation and better estimation of production and marketing costs. Furthermore, studios will now be able to collect features and information prior to when a project comes live, and then relate these features to the performance of content. This opens up a whole new world of allowing studios to predict demand and eventually forecast performance before content comes live. In the past content performance could only be forecasted after it said content was produced, but now, studios will be able to associate production features, like settings in a scene, to expected success of content. 

The project could also allow a network of characters to be built from the metadata dataset. The occurrences of actors in a screen and the participation in dialogues can be recorded. This information could then be tied to the success of a scene, thereby allowing for better content production value. 

With the some of this information, studios can get a gauge on what legal contracts needed to be drafted, prior to the commencement of production, and also foresee any legal issues that they would traditionally be blindsided from.

Studios can establish relationships with undiscovered content creators and talent. The sheer increase in the number of scripts that would now be reviewed would allow for the discovery of new projects that would have otherwise got lost in the manual process.
 
There will be challenges along the way. I do not expect this to be a turn-key solution. The main challenge will be user adoption. Changing the way things have been done for almost a century is going to be difficult. Studios will have to drive this change since they have the most leverage in the ecosystem.