# Freight 2.0

#### Keywords {-}
freight, truck, marketplaces, carrier, ship

## A Broken Backbone

The trucking industry is the lifeblood of moving goods around the country. It represents 70 percent of the nation's freight volume. Trucking forms the physical backbone of e-commerce as well as person-to-person shipments. Trucking companies' revenue reached $700 billion in 2017, making up approximately 80 percent of the $900 billion generated by all transportation modes. 

Yet the trucking industry is fraught with inefficiency. 

The industry is broken down into three roles. Understanding the roles will help highlight where these inefficiencies lie:
1. Shippers (the demand): These are companies that need their product moved - from small manufacturers all the way up to large brands like Nike, Ralph's, etc.
2. Carriers (the supply): These are the fleets and the independent truck drivers. The carrier market is extremely fragmented. Most are independently owned and operated - 90% of carriers have fewer than 6 trucks in their fleet.
3. Brokers (the intermediaries): There are about 13000 brokers in this country and match demand with supply. They maintain their success because of the fragmentation in the shipping and carrying industries. Brokers charge high commission (15-20%) and are known for exploitative practices such as "QuickPay", where drivers are given the option to avoid having to wait for weeks to receive payment on loads delivered. This comes at an additional charge that is imposed by a broker, typically in the range of an additional 3-5% commission. 

The entire industry runs on archaic software. No data is captured and none of the software systems communicate with each other. Almost 70% of shippers do not use any software at all, and still rely on paper records. As it turns out, of all the miles that truck drivers travel across the country, 40% of those trucks are empty. Let's think about that-40% of the carbon impact from trucks today is because of empty mileage. Drivers often sit idle, waiting hours for pick-ups, and driving routes with no loads if their firm is beaten out by another carrier. 


## A Marketplace for Freight

There is huge opportunity in this industry - everything from asset tracking to electronic document management; shipment management and optimization to analytics for brokers and shippers; tracking and fleet management (both GPS hardware and software) to messaging, and of course payments.

Our solution is a platform that will attempt to transform the matching between shippers and carriers. Currently the only way to locate drivers is by calling them, which also makes it extremely hard to filter for quality. This manual process results not only in wasted time but also in sub-optimal pricing and routes. Hours are wasted on waiting for quotes and booking trucks. 

The economy of "moving stuff" can be thought of as trying to hail a car through a ride-sharing service. Our system will allow shippers to post requests for handling freight, but instead of broadcasting that job to the entire trucking universe, it will immediately find a carrier in the right place with the right equipment. A dynamic pricing model based on automatic auction bidding will be used. This will facilitate instantaneous price agreement between the parties. Since both, shippers and carriers, will now be on the same platform, our system will allow for real-time tracking of shipments and delivery for shippers. Near-immediate payment for carriers will become the norm. 

This solution will be implemented through a matching app. Mobile and dektop versions of the app will be available. The success of our network will depend on a rigorous vetting process for carriers. Safety records from insurance companies and regulators will need to be provided in order for carriers to join. Ongoing metrics on performance, like on-time pickup and delivery, will be tracked.

## Vision

We are trying to make headway in a highly fragmented business. Growing a strong network of carriers and shippers will be difficult. You can have the best app in the world, but unless you can offer a significant amount of volume to carriers, you're not going to be able to get good rates with those carriers. And unless shippers get a better rate, they have very little or no incentive to switch over from using existent companies. Performance metrics, reduced paper load, immediate payments and better tracking are all perks that will be secondary to getting a preferential rate from carriers. We do believe however, that once said network is established, there is a very high opportunity for two-sided network effects to kick in. To kick start the flywheel we might consider subsidizing carrier fees. 

Our vision is for a world that operates efficiently. Technology can bring ease and efficiency to the supply chain industry and improve trucking. As more truckers and companies shipping freight become part of our network, our software will create smarter routes that efficiently batch shipments for our truck drivers, helping them and their small businesses thrive, saving on transportation costs and curtailing environmental waste.
