---
title: "W201 Portfolio"
author: "Nishant Hegde"
date: "MIDS Spring 2018"
site: bookdown::bookdown_site
documentclass: book
bibliography: references.bib
link-citations: yes
biblio-style: apalike
---

<!-- This won't be displayed but it will initialize your R session. Add any R libraries you need here. -->
```{r init,include=FALSE,echo=FALSE}
library(magrittr)
readLines('https://www.zotero.org/api/users/4669241/items/top?limit=25&format=bibtex&key=4LlCKGnrNfKwEZ1hphoHyaaw&v=1') %>% writeLines('references.bib')
```


# Welcome! {-}

You've reached the w201 website for Nishant Hegde. Meet Benjamin Franklin (not my dog)!

<!-- Below this line is just examples of how you can embed video from Google Drive. First you have to enable sharing, then just get the object ID which is that long string between d/ and /preview and will also be appended to any sharing link you generate for your video. -->
<p>
```{r hello-benji,echo=FALSE,fig.cap='Hello Benjamin Franklin!',fig.align='center'}
knitr::include_url('https://drive.google.com/file/d/0B6bobRDQR96iVEV3SXJJal9CczQ/preview')
```

### Abstract of my first cool idea {-}

My first big idea is an automatic script parsing tool that can be used by studios to improve their greenlighting.

## About the author {-}

Wannabe data scientist.

*Updated: `r Sys.Date()`*
